In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('../data/events.csv', low_memory=False)
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iPhone 5s,Muito Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Busco std de cantidad distinta de modelos vistos por usuario

In [9]:
df_features = df.loc[df['event']=='viewed product', :]
agrupado = df_features.groupby(['person', 'model']).agg({'timestamp':'count'})

In [10]:
agrupado.reset_index(inplace=True)
agrupado.columns = ['person', 'model', 'times viewed']

In [11]:
agrupado = agrupado.groupby('person').agg({'times viewed':['mean', 'std', 'sum']})
agrupado.replace(to_replace=np.nan, value=0, inplace=True)

In [12]:
agrupado.to_csv('../data/viewed_product_stats.csv')

### Busco los top k sku para los usuarios

In [13]:
df_features = df.loc[df['sku']!=np.nan, :]
df_features.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-18 00:11:59,viewed product,4886f805,NaN,9288.0,Samsung Galaxy J7 Prime,Excelente,32GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-18 00:11:27,viewed product,ad93850f,NaN,304.0,iPhone 5s,Muito Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-05-18 00:11:16,viewed product,0297fc1e,NaN,6888.0,iPhone 6S,Muito Bom,64GB,Prateado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-18 00:11:14,viewed product,2d681dd8,NaN,11890.0,iPhone 7,Bom,128GB,Vermelho,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-18 00:11:09,viewed product,cccea85e,NaN,7517.0,LG G4 H818P,Excelente,32GB,Branco,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
skus = df_features.loc[(df_features['event']=='viewed product') & (df_features['sku']!=np.nan) , ['sku', 'person']]

In [15]:
skus_grouped = skus.groupby('person').agg({'sku':['mean', 'std']})

In [16]:
skus_grouped.columns = ['sku mean', 'sku std']

In [17]:
skus_grouped.replace(to_replace=np.nan, value=0, inplace=True)

In [18]:
skus_grouped

              sku mean      sku std
person
00091926   7191.534946  2991.000923
00091a7a   5487.666667  3646.651798
000ba417   6661.385621  3684.488701
000c79fe   9944.000000     0.000000
000e4d9e   4323.631268  3013.501676
000e619d   6845.714286  4553.713323
001001be   2843.097561  1973.298619
0010e89a   4571.000000     0.000000
0016c4b5   8471.000000     0.000000
001802e4   9411.500000  2896.566301
0019e639   4469.111111  3565.539247
001a2273   6289.666667  4620.210933
001b0bf9  13019.000000   326.683333
001ca5ee   6185.269231  4087.168487
001dfc31   9003.055556  1539.883092
001e9aea   3783.000000  2177.974920
0020152e   5227.500000  2861.661143
00202cdb   2782.214286  1709.599961
0022965d   6430.133333  2446.673014
0027574e   5425.735294  3216.718314
00295d74   7292.181818  1748.069553
002aea56   6978.484472  3311.770265
002b0188   6358.500000  4066.346864
002e74b2   2833.500000     0.707107
002ed810   8908.227273  1831.777927
002fb981   1996.600000  1798.495436
00317e49   9594.000000  3948.902041
0031c75f   6773.653846  5863.693041
00344873   9085.428571  1186.478383
003476c0   2663.000000  1518.375184
...                ...          ...
ffc670b3   4306.818182  3140.645367
ffcaae19   7316.037037  2948.384010
ffcaeaae   7961.500000  2277.377539
ffccd5a1   6785.500000  2027.159860
ffcf952b   7407.377358  4430.657006
ffd41214  10327.800000  4399.585401
ffd62616   8051.636364  2981.603537
ffd9756a   2711.000000     0.000000
ffda14ca    178.000000     0.000000
ffdafc72   6671.391304  1876.339588
ffddd0ec  10047.583333  2783.951556
ffde3628  10335.429577  2159.844240
ffe066cc   4311.583333  3346.119049
ffe53446   5927.754545  4722.561759
ffe7e848   8626.322581  3777.184921
ffeb80c5   6371.000000     0.000000
ffebdbc9  13291.291667  1073.400346
ffecdf29   3727.666667  3842.425579
ffecea3d  10336.800000     0.836660
ffed0342   6850.130841  3901.442945
ffed3d0e   6875.000000     0.000000
ffee0f18   6412.148922  4193.327787
ffef83e6   9184.946108  3002.162839
fff1659c   8503.894737  3721.766156
fff1b11a  13178.684211  1308.448065
fff1caee  10533.000000     0.000000
fff2bdde   8032.441176  3865.197883
fff72025   6139.809524  3900.194068
fff78145  10497.806452  2772.043391
fffd1246   4540.500000  2810.865288

[37130 rows x 2 columns]